services:

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${PORT_API}:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - API_AUTH_URL
    depends_on:
      service_auth:
        condition: service_started
    restart: on-failure

  service_auth:
    container_name: service_auth
    build:
      context: ./service_authentification
      dockerfile: Dockerfile
    ports:
      - "${PORT_AUTH}:8001"
    environment:
      - DATABASE_USER_URL
      - SECRET_KEY
      - ALGORITHM
      - TOKEN_EXPIRE_MINUTES
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      user_db:
        condition: service_started
    restart: on-failure

          
  user_db:
    image: postgres
    container_name: user_db
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: user_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user

  api_db:
    image: postgres
    container_name: api_db
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_DB: api_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user


  service_tensorflow:
    container_name: service_tensorflow
    build:
      context: ./services_training/tensorflow_model
      dockerfile: Dockerfile
    ports:
      - "${PORT_TENSORFLOW}:8003"
    environment:
      - DATABASE_TENSORFLOW_URL
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      api_db:
        condition: service_started
    restart: on-failure


  service_pytorch:
    container_name: service_pytorch
    build:
      context: ./services_training/pytorch_model
      dockerfile: Dockerfile
    ports:
      - "${PORT_PYTORCH}:8002"
    environment:
      - DATABASE_PYTORCH_URL
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      api_db:
        condition: service_started
      kafka:
        condition: service_started
    restart: on-failure
        
  bdd_service:
    container_name: bdd_service
    build:
      context: ./bdd_service
      dockerfile: Dockerfile
    ports:
      - "${PORT_SERVICE_BDD}:8004"
    environment:
      - DATABASE_USER_URL
      - SECRET_KEY
      - ALGORITHM
      - TOKEN_EXPIRE_MINUTES
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      user_db:
        condition: service_started
    restart: on-failure  


  adminer:
    image: adminer
    restart: always
    ports:
      - "${PORT_ADMINER}:8080"

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        VITE_API_GATEWAY_URL: ${VITE_API_GATEWAY_URL}
        VITE_API_AUTH_URL: ${VITE_API_AUTH_URL}
    container_name: frontend
    ports:
      - "${PORT_FRONT}:80"
    restart: unless-stopped

  kafka:
    image : confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "${PORT_KAFKA}:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"
      CLUSTER_ID: "Qi0fGmQDTMuu9eKmM3ixnA"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
    volumes:
      - kafka_kafka:/var/lib/kafka/data

networks:
  backend:
    driver: bridge

volumes:
  kafka_kafka:


#- DATABASE_LOG_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_LOG}
#- DATABASE_PM1_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_PM1}